apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: my-cluster
  namespace: flux-system
spec:
  interval: 10s
  path: ./deployments
  prune: true
  suspend: true
  sourceRef:
    kind: GitRepository
    name: flux-system
